### ISSUE TITLE
[DataCap Application] Momoshop

### ISSUE THREAD

**Issue by GalateaLi88** [1475Notary/1475-Allocator#1]
### Version

1

### DataCap Applicant

Galatea

### Project ID

no

### Data Owner Name

Momoshop

### Data Owner Country/Region

China

### Data Owner Industry

Other

### Website

https://www.momoshop.com.tw/

### Social Media Handle

Slack: Galatea

### Social Media Type

Slack

### What is your role related to the dataset

Data Preparer

### Total amount of DataCap being requested

100

### Unit for total amount of DataCap being requested

TiB

### Expected size of single dataset (one copy)

20

### Unit for expected size of single dataset

TiB

### Number of replicas to store

5

### Weekly allocation of DataCap requested

100

### Unit for weekly allocation of DataCap requested

TiB

### On-chain address for first allocation

f1nh77gas227kn3mprrcbpou5wwkfb4n52vemgpta

### Data Type of Application

Public, Open Commercial/Enterprise

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Momo shopping is under Fubon Media Technology which is the leading online retailer in Taiwan. Our business includs Motian Mall, TV shopping and catalog shopping. Headquartered in Taiwan, our group is also actively establishing international markets. On the mainland, Fubon Gehua (Beijing) Trade Co., Ltd. was established in May 2011. In March 2014, our company established TVD momo in Thailand as a joint venture.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
We want to store pictures and videos of these products which showed on our website.
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### If you are a data preparer. What is your location (Country/Region)

China

### If you are a data preparer, how will the data be prepared? Please include tooling used and technical details?

```text
We use lotus to transform data into car files, then we store these files into filecoin.
```

### Has this dataset been stored on the Filecoin network before? If so, please explain and make the case why you would like to store this dataset again to the network. Provide details on preparation and/or SP distribution.

```text
We have stored some data on Filecoin, and we take new data this time.
```

### Please share a sample of the data

```text
https://drive.google.com/file/d/1RtKB_Q1flCoeN6N1Gth4c581kwbZcIdM/view?usp=sharing
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

1.5 to 2 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, South America, Europe

### How will you be distributing your data to storage providers

HTTP or FTP server, Shipping hard drives

### How did you find your storage providers

Slack, Big Data Exchange

### Please list the provider IDs and location of the storage providers you will be working with.

```text
f01844232 US
f01084913 HongKong
f01807908 Spain
f02816097 China
f02363999 Singapore
```

### How do you plan to make deals to your storage providers

Boost client, Lotus client, Singularity

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by 1475Notary** [comment]
Based on the communication on slack, this client is real and the amount is not much to give.

**Comment by filecoin-watchdog** [comment]
checker:manualTrigger

**Comment by 1475Notary** [comment]
Close due to completion.
